/* GENERATED FILE */
import * as React from "react";
import type { Icon } from "../lib/types";
import IconBase from "../lib/IconBase";
import weights from "../defs/Minus";


/**
 * @regular ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 * @thin ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 * @light ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 * @bold ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 * @fill ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 * @duotone ![img](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjMDAwIj48cmVjdCB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGZpbGw9IiNGRkYiIHJ4PSI0IiByeT0iNCIvPgogIDxwYXRoIGQ9Ik04LjI1IDExaDcuNWEuNzUuNzUgMCAxIDEgMCAxLjVoLTcuNWEuNzUuNzUgMCAxIDEgMC0xLjVaIi8+Cjwvc3ZnPgo=)
 */
const I: Icon = React.forwardRef((props, ref) => (
  <IconBase ref={ref} {...props} weights={weights} viewBox="0 0 24 24" />
));

I.displayName = "MinusIcon";

export const Minus = I;
export { I as MinusIcon };
